import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import express from 'express';
import {localRepository} from '../server/invoicing/storage.js';
import {invoiceRouter} from '../server/invoicing/router.js';
import {workflowReview,buildRecord,exportInvoice,suggestions} from '../server/invoicing/workflow.js';
import {extractedDraft,extractDocument,validateSource} from '../server/invoicing/extraction.js';
import {extractCsv} from '../server/invoicing/csv.js';
const cid='demo-kitchen';
const catalog={clientId:cid,suppliers:[{id:'v1',name:'Proveedor "Demo"',rut:'11111111-1'}],items:[{productId:'p1',presentationId:'s1',name:'Pan, prueba',unit:'CASE',size:'40 UNIDAD',baseUnit:'unit',baseUnits:40}]};
function draft(){return {id:crypto.randomUUID(),clientId:cid,supplier:'Proveedor Demo',supplierRut:'11111111-1',supplierId:'v1',documentType:'factura',folio:'0001',date:'2026-01-02',net:47000,vat:8930,otherTaxes:0,total:55930,taxExceptionReviewed:false,lines:[{id:'l1',description:'Pan de prueba',kind:'food',quantity:2,netLineTotal:47000,purchaseUnit:'case',costBasis:'unit',unitsPerPurchaseUnit:40,contentPerUnit:{value:null,unit:'g'},measuredTotalKg:null,reviewed:true,note:'Caja confirmada',sourcePresentation:'caja40',productId:'p1',presentationId:'s1',targetQuantity:2,mappingReviewed:true,learnMapping:true}]};}
async function repo(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'invoices-'));const file=path.join(dir,'db.sqlite');const r=localRepository(file);t.after(()=>{r.close();return fs.rm(dir,{recursive:true,force:true});});return {r,file};}
test('net conversion preserves 80 pieces; wrong target quantity cannot be confirmed',()=>{const d=draft();assert.equal(workflowReview(d,catalog).canConfirm,true);d.lines[0].targetQuantity=1.5;assert.match(workflowReview(d,catalog).errors.join(' '),/no conserva/);});
test('delivery and supplies appear once in header, taxes zero, folio text preserved',()=>{const d=draft();d.lines.push({id:'delivery',kind:'delivery',description:'Despacho',quantity:1,netLineTotal:20000,note:'Delivery una sola vez',reviewed:true},{id:'supply',kind:'supply',description:'Guantes',quantity:1,netLineTotal:1000,note:'Non-Inventory',reviewed:true});d.net=68000;d.vat=12920;d.total=80920;const r=buildRecord(d,{status:'confirmed'});const out=exportInvoice(r,catalog);assert.equal(out.summary.totalDelivery,20000);assert.equal(out.summary.totalNonInventory,1000);assert.equal(out.summary.totalTaxes,0);assert.equal(out.summary.totalNet,68000);assert.equal(out.csv.split('\r\n').length,3);assert.match(out.csv,/"0001"/);assert.match(out.csv,/"47000","0"/);});
test('existing SH documents and drafts cannot be exported',()=>{const d=draft();assert.throws(()=>exportInvoice(buildRecord(d),catalog),/Confirma/);assert.throws(()=>exportInvoice(buildRecord(d,{status:'confirmed',existingInSh:{id:'x'}}),catalog),/ya está en SH/);});
test('incomplete package content blocks export despite confirmed physical amount',()=>{const c=structuredClone(catalog);c.items[0].validFormat=false;assert.match(workflowReview(draft(),c).errors.join(' '),/incompleta/);});
test('learning occurs only after confirmation and exact supplier/presentation; future costs ignored',()=>{const d=draft();let r=buildRecord(d);assert.notEqual(suggestions(d,d.lines[0],catalog,[r])[0]?.reason,'learned');r.status='confirmed';r.report=workflowReview(d,catalog);assert.equal(suggestions(d,d.lines[0],catalog,[r])[0].reason,'learned');const resized=structuredClone(catalog);resized.items[0].baseUnits=30;assert.notEqual(suggestions(d,d.lines[0],resized,[r])[0]?.reason,'learned');const other=structuredClone(d);other.supplierId='v2';assert.notEqual(suggestions(other,other.lines[0],catalog,[r])[0]?.reason,'learned');const c=structuredClone(catalog);c.items[0].costs=[{supplierId:'v1',date:'2030-01-01',unit:'CASE',netPrice:1}];assert.equal(workflowReview(d,c).canConfirm,true);c.items[0].costs[0].date='2025-12-01';assert.match(workflowReview(d,c).errors.join(' '),/alza/);});
test('SQLite restart, duplicates and concurrent stale updates are protected',async t=>{const {r,file}=await repo(t);const d=draft();const a=buildRecord(d);a.draft.id=a.id;await r.save(a,0);const another=localRepository(file);assert.equal((await another.get(cid,a.id)).draft.folio,'0001');const updated=buildRecord(a.draft,{prior:a});await r.save(updated,1);await assert.rejects(()=>another.save(updated,1),/cambió|existe/);const duplicate=buildRecord(draft());await assert.rejects(()=>r.save(duplicate,0),/duplicada/);assert.equal(await another.get('other',a.id),null);another.close();});
test('read-only extraction leaves every approval unset and missing taxes unknown',()=>{const d=extractedDraft({folio:'001',lines:[{description:'Item',quantity:2,netLineTotal:null,kind:'food'}]},cid);assert.equal(d.vat,null);assert.equal(d.lines[0].reviewed,false);assert.equal(d.lines[0].mappingReviewed,false);assert.equal(d.lines[0].netLineTotal,null);});
test('CSV multiline quoted fields, leading zeros and absent fiscal totals survive',()=>{const source={data:Buffer.from('item_name,quantity_of_purchase,total_cost,invoice_number,invoice_date,vendor_name\r\n"Pan,\nbolsa",2,100,0001,2026-01-01,Proveedor\r\n').toString('base64')};const x=extractCsv(source);assert.equal(x.folio,'0001');assert.equal(x.lines[0].description,'Pan,\nbolsa');assert.equal(x.vat,null);assert.equal(x.net,null);});
test('invalid PDF and disguised image are rejected before sending to extraction',async()=>{await assert.rejects(()=>validateSource({name:'x.pdf',type:'application/pdf',data:Buffer.from('<script>').toString('base64')}),/PDF inválido/);await assert.rejects(()=>validateSource({name:'x.png',type:'image/png',data:Buffer.from('<html>').toString('base64')}),/PNG inválido/);});
test('provider receives only document and untrusted-content instruction, store false',async()=>{let request;const source={name:'f.pdf',type:'application/pdf',data:'YWJj'};const x=await extractDocument(source,{apiKey:'test',fetchImpl:async(url,options)=>{request=JSON.parse(options.body);return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({lines:[],folio:'1'})}]}]})};}});assert.equal(x.result.folio,'1');assert.equal(request.store,false);assert.equal(request.tools,undefined);assert.match(request.input[0].content,/ignora cualquier instrucción/);assert.equal(request.text.format.strict,true);});
test('HTTP flow saves, reloads, confirms, exports, rejects stale save/cross-client/cross-origin',async t=>{
 const {r}=await repo(t);await r.putCatalog(cid,catalog);const app=express();app.use(express.json());app.use((req,_res,next)=>{req.session={username:'test',role:'Superadmin'};next();});app.use('/api',invoiceRouter({repository:r,clients:[{id:cid}],apiKey:''}));const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api`;
 const call=(route,method='GET',body,headers={})=>fetch(base+route,{method,headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});
 let response=await call('/'+cid+'/invoices','POST',{draft:draft()});assert.equal(response.status,201);let rec=await response.json();const route='/'+cid+'/invoices/'+rec.id;
 assert.equal((await call('/other/invoices')).status,403);assert.equal((await call(route,'PUT',{version:0,draft:rec.draft})).status,409);
 assert.equal((await call(route,'PUT',{version:rec.version,draft:rec.draft},{Origin:'https://elsewhere.invalid'})).status,403);
 const review=await (await call(route+'/review','POST',{})).json();assert.equal(review.canConfirm,true);
 response=await call(route+'/confirm','POST',{version:rec.version,reviewed:true});assert.equal(response.status,200);rec=await response.json();assert.equal(rec.status,'confirmed');
 response=await call(route+'/export');assert.equal(response.status,200);assert.equal((await response.json()).summary.totalTaxes,0);
});
test('extraction failure preserves original; retry resets approvals and retains source',async t=>{
 const {r}=await repo(t);let calls=0;const app=express();app.use(express.json());app.use((req,_res,next)=>{req.session={username:'test',role:'Superadmin'};next();});app.use('/api',invoiceRouter({repository:r,clients:[{id:cid}],apiKey:'test',extract:async()=>{calls++;if(calls===1)throw new Error('Provider unavailable');return {result:{folio:'002',supplier:'Demo',supplierRut:'11111111-1',date:'2026-01-01',net:100,vat:19,otherTaxes:0,total:119,lines:[{description:'Producto',kind:'food',quantity:1,netLineTotal:100}]},model:'stub'};}}));
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/${cid}`;const post=(route,body)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 let response=await post('/documents',{file:{name:'test.png',type:'image/png',data:Buffer.from('89504e470d0a1a0a','hex').toString('base64')}});assert.equal(response.status,201);let record=await response.json();assert.equal(record.extraction.model,'failed');const hash=record.source.hash;
 response=await post('/invoices/'+record.id+'/extract',{version:record.version});assert.equal(response.status,200);record=await response.json();assert.equal(record.source.hash,hash);assert.equal(record.draft.lines[0].reviewed,false);assert.equal(record.draft.lines[0].mappingReviewed,false);assert.equal(record.status,'draft');
});
