import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {reviewDraft} from '../../server/invoicing/review.js';
import type {Draft,Line,Catalog,InvoiceRecord,CatalogItem} from './types';
import {buildPeriodOptions,invoicePeriod} from '../../server/invoicing/navigation.js';
import type {PeriodOption} from '../../server/invoicing/navigation.js';
import './review.css';
const id=()=>crypto.randomUUID();
const blankLine=():Line=>({id:id(),description:'',kind:'food',quantity:null,netLineTotal:null,purchaseUnit:'',costBasis:'',unitsPerPurchaseUnit:null,contentPerUnit:{value:null,unit:'g'},measuredTotalKg:null,reviewed:false,note:'',sourcePresentation:'',productId:'',presentationId:'',targetQuantity:null,mappingReviewed:false});
const blank=(clientId:string):Draft=>({id:id(),clientId,supplier:'',supplierRut:'',supplierId:'',documentType:'factura',folio:'',date:'',net:null,vat:null,otherTaxes:null,total:null,taxExceptionReviewed:false,lines:[blankLine()]});
const money=(n:number|null|undefined)=>n==null?'—':new Intl.NumberFormat('es-CL',{maximumFractionDigits:3}).format(n);
async function api(url:string,options:RequestInit={}){
 const r=await fetch('/api/invoicing'+url,{...options,headers:{'Content-Type':'application/json',...options.headers}});
 const data=await r.json().catch(()=>({error:'No se pudo conectar al módulo. Inicia sesión en el CMS.'}));
 if(!r.ok)throw new Error(data.error||`Error ${r.status}`);return data;
}
function download(name:string,text:string,type='application/json') {const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function NumberField({label,value,onChange}:{label:string;value:number|null|undefined;onChange:(v:number|null)=>void}){return <label>{label}<input type="number" min="0" step="any" value={value??''} onChange={e=>onChange(e.target.value===''?null:e.target.valueAsNumber)}/></label>;}
function CatalogChoice({items,line,onChange}:{items:CatalogItem[];line:Line;onChange:(c:Partial<Line>)=>void}){
 const [search,setSearch]=useState('');const selected=items.find(x=>x.presentationId===line.presentationId&&x.productId===line.productId);
 const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const options=items.filter(x=>x===selected||!search||norm(x.name+' '+x.size).includes(norm(search))).slice(0,80);
 if(selected&&!options.includes(selected))options.unshift(selected);
 return <><label>Buscar producto en el catálogo<input placeholder="Nombre del producto" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Producto y presentación SH<select value={selected?selected.productId+'|'+selected.presentationId:''} onChange={e=>{const [productId,presentationId]=e.target.value.split('|');onChange({productId:productId||'',presentationId:presentationId||'',mappingReviewed:false,targetQuantity:null,acknowledgePrice:false});}}><option value="">Seleccionar · {items.length} presentaciones disponibles</option>{options.map(x=><option key={x.productId+'|'+x.presentationId} value={x.productId+'|'+x.presentationId}>{x.name} · {x.unit} ({x.size}){x.validFormat===false?' · formato incompleto':''}</option>)}</select></label>{selected?.validFormat===false&&<p className="pending">Esta presentación tiene contenido incompleto. La exportación quedará bloqueada hasta validarlo.</p>}</>;
}
function App(){
 const [clients,setClients]=useState<{id:string;name:string}[]>([]);const [cid,setCid]=useState('');const [catalog,setCatalog]=useState<Catalog>({clientId:cid,items:[],suppliers:[]});
 const [period,setPeriod]=useState('');const [periods,setPeriods]=useState<PeriodOption[]>([]);const [loading,setLoading]=useState(false);const [editing,setEditing]=useState(false);
 const [list,setList]=useState<any[]>([]);const [record,setRecord]=useState<InvoiceRecord|null>(null);const [draft,setDraft]=useState<Draft>(blank(cid));const [dirty,setDirty]=useState(false);
 const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [report,setReport]=useState<any>(null);const [reviewed,setReviewed]=useState(false);const [auto,setAuto]=useState(false);const [manual,setManual]=useState(false);const [csvFolio,setCsvFolio]=useState('');const [storage,setStorage]=useState('');const [validationOnly,setValidationOnly]=useState(true);
 const calculation=reviewDraft(draft);const base='/'+cid;
 const refresh=async()=>setList(await api(base+'/invoices'));
 const options=buildPeriodOptions(list,periods);const visible=list.filter(r=>invoicePeriod(r)===period).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.folio).localeCompare(String(b.folio)));
 const selectedPeriod=options.find(p=>p.id===period);const clientName=clients.find(c=>c.id===cid)?.name;
 const resetEditor=()=>{setRecord(null);setDraft(blank(cid));setDirty(false);setReport(null);setReviewed(false);setEditing(false);};
 useEffect(()=>{api('/config').then(c=>{setClients(c.clients);setAuto(c.extractionEnabled);setStorage(c.storage);setValidationOnly(c.validationOnly!==false);}).catch(e=>setNotice(e.message));},[]);
 useEffect(()=>{let active=true;resetEditor();setPeriod('');setPeriods([]);setCatalog({clientId:cid,items:[],suppliers:[]});setList([]);setNotice('');setLoading(Boolean(cid));if(!cid)return;Promise.all([api(base+'/catalog'),api(base+'/invoices'),api(base+'/periods')]).then(([c,l,p])=>{if(active){setCatalog(c);setList(l);setPeriods(p);}}).catch(e=>{if(active)setNotice(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[cid]);
 useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const run=async(f:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await f();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
 const loadRecord=(r:InvoiceRecord)=>{setEditing(true);setRecord(r);setDraft(r.draft);setDirty(false);setReport(null);setReviewed(false);};
 const patch=(change:Partial<Draft>)=>{setDraft(d=>({...d,...change,taxExceptionReviewed:('net' in change||'vat' in change)?false:(change.taxExceptionReviewed??d.taxExceptionReviewed),lines:('supplierId' in change||'supplierRut' in change||'folio' in change||'date' in change)?d.lines.map(l=>({...l,mappingReviewed:false,acknowledgePrice:false})):change.lines??d.lines}));setDirty(true);setReport(null);setReviewed(false);};
 const linePatch=(n:number,c:Partial<Line>)=>patch({lines:draft.lines.map((l,i)=>i===n?{...l,...c,reviewed:c.reviewed??false,mappingReviewed:c.mappingReviewed??false,acknowledgePrice:c.acknowledgePrice??false}:l)});
 const acknowledge=(n:number,c:Partial<Line>)=>patch({lines:draft.lines.map((l,i)=>i===n?{...l,...c}:l)});
 const mayLeave=()=>!dirty||window.confirm('Hay cambios sin guardar. ¿Descartarlos para cambiar de vista?');
 async function open(rid:string){if(!mayLeave())return;await run(async()=>{loadRecord(await api(base+'/invoices/'+rid));});}
 async function save(){const r=await api(base+'/invoices'+(record?'/'+record.id:''),{method:record?'PUT':'POST',body:JSON.stringify({draft,version:record?.version})});loadRecord(r);await refresh();return r as InvoiceRecord;}
 async function upload(file:File|undefined){
  if(!file||!mayLeave())return;
  await run(async()=>{
   if(file.size>10*1024*1024)throw new Error('Máximo 10 MB por documento.');
   const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});
   const type=file.name.toLowerCase().endsWith('.csv')?'text/csv':file.type;
   setNotice(manual?'Guardando documento…':'Leyendo el documento. Puede tardar hasta dos minutos…');
   const r=await api(base+'/documents',{method:'POST',body:JSON.stringify({file:{name:file.name,type,data},manual:manual||!auto,folio:csvFolio})});
   loadRecord(r);setPeriod(invoicePeriod(r));await refresh();setNotice('Original y lectura guardados como borrador. Revisa cifras, formatos y equivalencias antes de confirmar.');
  });
 }
 async function check(){await run(async()=>{const r=dirty||!record?await save():record;setReport(await api(base+'/invoices/'+r.id+'/review',{method:'POST',body:'{}'}));});}
 const sourceUrl=record?.source?'/api/invoicing'+base+'/invoices/'+record.id+'/source':'';
 return <main>
  <header><div><span className="brand">BEVINCO / COCINA</span><h1>{validationOnly?'Validación de facturas':'Revisión de facturas'}</h1><p>{validationOnly?'Revisa el original, corrige los datos y guarda tu validación.':'Lee el original, valida la compra y prepara su importación.'}</p><a href="/" onClick={e=>{if(!mayLeave())e.preventDefault();}}>Volver al CMS</a></div><span className="badge">{storage==='local'?'Vista previa':'Cocina'} · {!editing?'Vista por período':dirty?'Cambios sin guardar':record?.status==='confirmed'?'Confirmada':'Borrador'}</span></header>
  <aside className="intro">{validationOnly?'Consulta tus facturas por cliente y período. Abre una factura para comparar el original con sus datos y revisar su estado.':<>Las compras se preparan con valores netos, antes de rendimiento y con Taxes en cero. La importación a SH es manual. Los duplicados se comprueban contra los registros guardados; verifica también el período de SH antes de importar. {storage==='local'?'Los documentos de esta prueba se guardan en el servidor local.':'Los borradores se conservan al guardarlos.'}</>}</aside>
  <section className="navigation" aria-label="Seleccionar cliente y período">
   <div className="navigation-title"><span className="eyebrow">TUS FACTURAS</span><p>Selecciona el cliente y luego el período que quieres revisar.</p></div>
   <div className="selectors"><label><span className="step">1</span> Cliente<select aria-label="Cliente" disabled={busy||loading} value={cid} onChange={e=>{if(mayLeave())setCid(e.target.value);}}><option value="">Seleccionar cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><span className="selector-arrow" aria-hidden="true">→</span><label><span className="step">2</span> Período<select aria-label="Período" disabled={!cid||busy||loading} value={period} onChange={e=>{if(mayLeave()){resetEditor();setPeriod(e.target.value);setNotice('');}}}><option value="">{loading?'Cargando períodos…':!cid?'Primero elige un cliente':'Seleccionar período'}</option>{options.map(p=><option key={p.id} value={p.id}>{p.label} · {list.filter(r=>invoicePeriod(r)===p.id).length} {list.filter(r=>invoicePeriod(r)===p.id).length===1?'factura':'facturas'}</option>)}</select></label></div>
  </section>
  {notice&&<p role="status" className="notice">{notice}</p>}
  {!period?<section className="navigation-empty"><span className="empty-symbol" aria-hidden="true">▤</span><h2>{!cid?'Comienza por elegir un cliente':loading?'Cargando períodos…':'Elige un período'}</h2><p>{!cid?'Aquí encontrarás sus facturas, organizadas por período.':'Verás únicamente las facturas del período seleccionado.'}</p></section>:<>
  <section className="saved"><div className="section-title"><div><span className="eyebrow">{clientName} / COCINA</span><h2>{selectedPeriod?.label||'Facturas del período'}</h2><p className="muted">{period==='unassigned'?'Documentos todavía sin un período SH registrado.':'Períodos registrados en el módulo; esta vista no cambia el período en Sculpture.'}</p></div><span className="count-badge">{visible.length} {visible.length===1?'factura':'facturas'}</span></div>
   <div className="period-summary"><div><span>Neto documental</span><strong>${money(visible.reduce((sum,r)=>sum+(r.net??0),0))}</strong></div><div><span>En Sculpture</span><strong>{visible.filter(r=>r.existingInSh).length}</strong></div><div><span>Por revisar</span><strong>{visible.filter(r=>r.status!=='confirmed'&&!r.existingInSh).length}</strong></div></div>
   {visible.length?<div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th>Fecha</th><th>Proveedor / folio</th><th>Neto</th><th>Estado</th><th><span className="sr-only">Abrir factura</span></th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className={r.id===record?.id?'active-row':''}><td>{r.date?r.date.split('-').reverse().join('/'):'Sin fecha'}</td><td><strong>{r.supplier||'Sin proveedor'}</strong><span>Factura {r.folio||'sin folio'}</span></td><td className="amount">${money(r.net)}</td><td><span className={'status-pill '+(r.existingInSh?'in-sh':r.status==='confirmed'?'confirmed':'draft')}>{r.existingInSh?'En SH':r.status==='confirmed'?'Confirmada':'Por revisar'}</span></td><td><button disabled={busy} onClick={()=>void open(r.id)}>Abrir</button></td></tr>)}</tbody></table></div>:<div className="period-empty"><h3>No hay facturas en esta vista</h3><p>Puedes abrir un documento nuevo o elegir otro período.</p></div>}
  </section>
  <details className="intake"><summary>Agregar una factura</summary><p>Los documentos nuevos quedan en «Sin período asignado» hasta registrar su período en SH.</p><div className="toolbar"><label className="upload">Abrir PDF, foto o CSV<input disabled={busy} aria-label="Abrir factura" type="file" accept="application/pdf,image/jpeg,image/png,image/webp,text/csv,.csv" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label><label className="check"><input type="checkbox" checked={manual||!auto} disabled={!auto||busy} onChange={e=>setManual(e.target.checked)}/>Ingreso manual</label><label>Folio para CSV con varias facturas<input value={csvFolio} onChange={e=>setCsvFolio(e.target.value)} placeholder="Solo para CSV"/></label><button disabled={busy} onClick={()=>{if(mayLeave()){resetEditor();setPeriod('unassigned');setEditing(true);}}}>Nueva manual</button></div></details>
  </>}
  {editing&&<>
  {record?.existingInSh&&<p className="notice">Esta factura ya está en SH (registro {record.existingInSh.id}). Puedes revisar y guardar sus datos; la exportación está bloqueada para evitar duplicarla.</p>}
  <fieldset disabled={busy} className="edit-fieldset"><div className="workspace"><section className="viewer"><h2>Documento original</h2>{record?.source?<><p>{record.source.name}</p><a href={sourceUrl} target="_blank" rel="noreferrer">Abrir original en otra pestaña</a>{record.source.type==='application/pdf'?<iframe title="Factura original" src={sourceUrl}/>:record.source.type.startsWith('image/')?<img alt="Factura original" src={sourceUrl}/>:<p>Original CSV conservado. Ábrelo para ver todas sus filas.</p>}</>:<div className="empty">Abre una factura PDF o una foto para revisarla aquí.</div>}{record?.source&&auto&&<button onClick={()=>{if(window.confirm('Volver a leer reemplaza los datos guardados por una nueva lectura sin confirmar. ¿Continuar?'))void run(async()=>{loadRecord(await api(base+'/invoices/'+record.id+'/extract',{method:'POST',body:JSON.stringify({version:record.version})}));await refresh();setNotice('Nueva lectura guardada. Requiere revisión.');});}}>Volver a leer original</button>}<p className="muted">{record?'Guardado: '+new Date(record.updatedAt).toLocaleString('es-CL'):'Todavía no guardado'}</p>{draft.warnings?.length? <details><summary>Observaciones de la lectura automática</summary><ul>{draft.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>:null}</section>
  <section className="editor"><h2>Datos de la factura</h2><div className="fields"><label>Proveedor documental<input value={draft.supplier} onChange={e=>patch({supplier:e.target.value})}/></label><label>RUT proveedor<input value={draft.supplierRut} onChange={e=>patch({supplierRut:e.target.value})}/></label><label>Folio<input value={draft.folio} onChange={e=>patch({folio:e.target.value})}/></label><label>Fecha<input type="date" value={draft.date} onChange={e=>patch({date:e.target.value})}/></label></div><label>Proveedor registrado en SH<select value={draft.supplierId??''} onChange={e=>patch({supplierId:e.target.value})}><option value="">Seleccionar proveedor</option>{catalog.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
  <div className="section-title"><h2>Productos y cargos</h2><button onClick={()=>patch({lines:[...draft.lines,blankLine()]})}>Agregar línea</button></div>
  {draft.lines.map((line,i)=><article className="line" key={line.id}><div className="section-title"><h3>Línea {i+1}</h3><button onClick={()=>{if(window.confirm('¿Quitar esta línea del borrador?'))patch({lines:draft.lines.filter((_,n)=>n!==i)});}}>Quitar</button></div><label>Descripción en factura<input value={line.description} onChange={e=>linePatch(i,{description:e.target.value})}/></label>
  <label>Tipo<select value={line.kind} onChange={e=>linePatch(i,{kind:e.target.value as Line['kind']})}><option value="food">Alimento</option><option value="delivery">Despacho · encabezado</option><option value="supply">Insumo no alimentario · encabezado</option></select></label>
  {line.printedLineTotal!=null&&<p className="muted">Lectura original: importe ${money(line.printedLineTotal)} · precio ${money(line.printedUnitPrice)}{line.priceIncludesVat?' con IVA':''}. Comprueba el neto antes de usarlo.</p>}
  <div className="fields"><NumberField label="Cantidad comprada" value={line.quantity} onChange={v=>linePatch(i,{quantity:v})}/><NumberField label="Importe neto de la línea ($)" value={line.netLineTotal} onChange={v=>linePatch(i,{netLineTotal:v})}/></div>
  {line.kind==='food'&&<><label>Formato original / contenido recibido<input placeholder="Ej.: caja de 40 panes" value={line.sourcePresentation??''} onChange={e=>linePatch(i,{sourcePresentation:e.target.value})}/></label><div className="fields"><label>Unidad de compra<select value={line.purchaseUnit} onChange={e=>linePatch(i,{purchaseUnit:e.target.value})}><option value="">Por confirmar</option>{[['kg','Kilos'],['g','Gramos'],['L','Litros'],['ml','Mililitros'],['unit','Unidad / envase'],['case','Caja / pack']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>Costear por<select value={line.costBasis} onChange={e=>linePatch(i,{costBasis:e.target.value})}><option value="">Por confirmar</option><option value="kg">Kilo</option><option value="unit">Unidad</option><option value="L">Litro</option></select></label></div>
  {['unit','case'].includes(line.purchaseUnit)&&<><NumberField label="Unidades contenidas por formato" value={line.unitsPerPurchaseUnit} onChange={v=>linePatch(i,{unitsPerPurchaseUnit:v})}/>{line.costBasis!=='unit'&&<div className="fields"><NumberField label="Contenido de cada unidad" value={line.contentPerUnit.value} onChange={v=>linePatch(i,{contentPerUnit:{...line.contentPerUnit,value:v}})}/><label>Unidad del contenido<select value={line.contentPerUnit.unit} onChange={e=>linePatch(i,{contentPerUnit:{...line.contentPerUnit,unit:e.target.value}})}>{['g','kg','ml','L'].map(v=><option key={v}>{v}</option>)}</select></label></div>}</>}
  {line.costBasis==='kg'&&<NumberField label="Peso real total (kg, opcional)" value={line.measuredTotalKg} onChange={v=>linePatch(i,{measuredTotalKg:v})}/>}
  <CatalogChoice items={catalog.items} line={line} onChange={c=>linePatch(i,c)}/><NumberField label="Cantidad en la presentación SH elegida" value={line.targetQuantity} onChange={v=>linePatch(i,{targetQuantity:v})}/>
  {report?.suggestions?.[i]?.length>0&&<details><summary>Sugerencias del catálogo · requieren revisión</summary>{report.suggestions[i].map((s:any)=><button key={s.presentationId} onClick={()=>linePatch(i,{productId:s.productId,presentationId:s.presentationId,targetQuantity:s.factor&&line.quantity?line.quantity*s.factor:null})}>{s.name} · {s.size}{s.reason==='learned'?' · equivalencia confirmada anteriormente':''}</button>)}</details>}
  </>}
  <label>Aclaración / tratamiento del cargo<input value={line.note} onChange={e=>linePatch(i,{note:e.target.value})}/></label><label className="check"><input type="checkbox" checked={line.reviewed} onChange={e=>acknowledge(i,{reviewed:e.target.checked})}/>Verifiqué cantidad, contenido e importe neto.</label>
  {line.kind==='food'&&<><label className="check"><input type="checkbox" checked={line.mappingReviewed??false} onChange={e=>acknowledge(i,{mappingReviewed:e.target.checked})}/>Confirmo producto, presentación y cantidad SH.</label><label className="check"><input type="checkbox" checked={line.learnMapping??false} onChange={e=>acknowledge(i,{learnMapping:e.target.checked})}/>Recordar esta equivalencia para el mismo proveedor y formato.</label><label className="check"><input type="checkbox" checked={line.provisional??false} onChange={e=>linePatch(i,{provisional:e.target.checked,learnMapping:false})}/>Criterio provisional autorizado (explicar arriba).</label><label className="check"><input type="checkbox" checked={line.acknowledgePrice??false} onChange={e=>acknowledge(i,{acknowledgePrice:e.target.checked})}/>Revisé el alza de precio señalada (explicar arriba).</label></>}
  {calculation.results[i]?.cost&&<p className="cost">{money(calculation.results[i].cost!.baseQuantity)} {line.costBasis} · ${money(calculation.results[i].cost!.netCostPerBaseUnit)} netos/{line.costBasis}</p>}
  </article>)}
  <h2>Conciliación documental</h2><p>Los impuestos se conservan en el documento. En SH siempre se preparan en cero.</p><div className="fields">{([['net','Neto documental ($)'],['vat','IVA documental ($)'],['otherTaxes','Otros impuestos ($)'],['total','Total documental ($)']] as const).map(([key,label])=><NumberField key={key} label={label} value={draft[key]} onChange={v=>patch({[key]:v})}/>)}</div><label className="check"><input type="checkbox" checked={draft.taxExceptionReviewed} onChange={e=>patch({taxExceptionReviewed:e.target.checked})}/>Revisé el tratamiento de IVA si es distinto del 19%.</label>
  <p>Suma neta de líneas: <strong>${money(calculation.sum)}</strong></p>
  <div className="toolbar"><button onClick={()=>void run(async()=>{await save();setNotice('Borrador guardado.');})}>Guardar borrador</button><button className="primary" onClick={()=>void check()}>Revisar y buscar equivalencias</button><button onClick={()=>download('factura-borrador.json',JSON.stringify({version:1,status:'draft',invoice:draft},null,2))}>Descargar respaldo</button></div>
  {report&&<div className={report.canConfirm?'summary ready':'summary'}><h2>{report.canConfirm?'Revisión lista para confirmar':`${report.errors.length} puntos pendientes`}</h2><ul>{report.errors.map((e:string,i:number)=><li key={i}>{e}</li>)}</ul><details><summary>Costos y referencias</summary><ul>{report.warnings.map((w:string,i:number)=><li key={i}>{w}</li>)}</ul></details><p>Delivery: ${money(report.delivery)} · Non-Inventory: ${money(report.nonInventory)} · Taxes: $0 · Total neto: ${money(report.shTotal)}</p><label className="check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Revisé el original y confirmo estos datos.</label><button disabled={!report.canConfirm||!reviewed||dirty} onClick={()=>void run(async()=>{const r=await api(base+'/invoices/'+record!.id+'/confirm',{method:'POST',body:JSON.stringify({version:record!.version,reviewed:true})});loadRecord(r);await refresh();setNotice('Revisión confirmada y guardada. No se ha enviado nada a SH.');})}>Confirmar revisión</button></div>}
  {!validationOnly&&record?.status==='confirmed'&&!dirty&&!record.existingInSh&&<button className="primary" onClick={()=>void run(async()=>{const out=await api(base+'/invoices/'+record.id+'/export');download('productos-'+draft.folio+'.csv',out.csv,'text/csv;charset=utf-8');download('encabezado-'+draft.folio+'.json',JSON.stringify(out.summary,null,2));setNotice('CSV y resumen de cargos preparados. Asigna total_cost a Ext. Price al importar; aplica Delivery/Non-Inventory una sola vez y verifica Taxes=0.');})}>Preparar CSV + cargos del encabezado</button>}
  </section></div></fieldset></>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
